apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dcox
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-dcox@sha256:f0eba018d866562d7f0d8142e1faf5edf18a9de81c226b1e4b3d0986da2c66f7
        name: my-nodejs
        resources: {}
status: {}
